### set configs
set -g prefix C-a
set -g mode-keys vi
set -g mouse off
#set -g status-utf8 on 		# 状态栏支持utf8

# Add truecolor support
set-option -ga terminal-overrides ",*256col*:Tc"
# Default terminal is 256 colors
set -g default-terminal "screen-256color"

set-option -g default-command /bin/bash

### Unbind keys
unbind C-b 
unbind '"'
unbind %
unbind v 
unbind y 


### Rebind keys

bind C-a send-prefix

bind-key p previous-window
bind-key n next-window

bind - splitw -v -c '#{pane_current_path}'
bind = splitw -h -c '#{pane_current_path}'

bind -r k select-pane -U
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

bind -r ^k resizep -U 10
bind -r ^j resizep -D 10
bind -r ^h resizep -L 10
bind -r ^l resizep -R 10

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-mode-vi
#bind p pasteb

bind R source-file '~/.tmux.conf'

### List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# linebar color
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "ram-usage"
set -g @dracula-cpu-usage-colors "dark_gray"
set -g @dracula-show-timezone false
set -g @dracula-day-month false 
set -g @dracula-military-time false 
set -g @dracula-show-left-icon gabriel
set -g @dracula-show-fahrenheit false

### run configs 
run '~/.tmux/plugins/tpm/tpm'
run '~/.tmux/plugins/tmux-resurrect/resurrect.tmux'

