return {
  {
    "xiyaowong/transparent.nvim",
    opts = {
      extra_groups = { -- table/string: additional groups that should be cleared
        -- In particular, when you set it to 'all', that means all available groups
        "BqfPreviewFloat",
        "NormalFloat",
        "NormalNC",
        "NvimTreeNormal",
        "NeoTreeTabInactive",
        "LineNr",
        "CursorColumn",
        "CursorLine",
        "CursorLineNr",
        "FloatBorder",
        "WinBar",
        "WinBarNC",
        "TreesitterContext",
        "Pmenu",
        "DapUIPlayPause",
        "DapUIRestart",
        "DapUIStop",
        "DapUIStepOut",
        "DapUIStepBack",
        "DapUIStepInto",
        "DapUIStepOver",
        "DapUIPlayPauseNC",
        "DapUIRestartNC",
        "DapUIStopNC",
        "DapUIStepOutNC",
        "DapUIStepBackNC",
        "DapUIStepIntoNC",
        "DapUIStepOverNC",
        "SignColumn",
        "StatusLine",
        "TelescopeBorder",
        "TelescopeNormal",
        "TelescopePreviewNormal",
        "TelescopeResultsNormal",
        "TelescopePromptNormal",
        "TabLineFill",
        "TreesitterContextLineNumber",
        "QuickFixLine",
        "Pmenu",
        "PmenuSel",
        "PmenuSbar",
        "PmenuThumb",
        "NotifyINFOBody",
        "NotifyWARNBody",
        "NotifyERRORBody",
        "NotifyDEBUGBody",
        "NotifyTRACEBody",
        "NotifyINFOBorder",
        "NotifyWARNBorder",
        "NotifyERRORBorder",
        "NotifyDEBUGBorder",
        "NotifyTRACEBorder",
        "WhichKeyFloat",
        "NeoTreeNormal",
        "NeoTreeNormalNC",
        "NeoTreeEndOfBuffer",
        "NeoTreeTabActive",
        "NeoTreeTabSeparatorInactive",
        "NeoTreeTabSeparatorActive",
        "AerialNormal",
        "AerialNormalNC",
        "GrugFarNormal",
        "GrugFarHelpHeader",
        "BlinkCmpMenu",
        "BlinkCmpMenuBorder",
        "BlinkCmpDoc",
        "BlinkCmpDocBorder",
        "BlinkCmpDocSeparator",
        "BlinkCmpSignatureHelp",
        "BlinkCmpSignatureHelpBorder",
        "WhichKeyNormal",
        "WhichKeyBorder",
        "WhichKeyTitle",
        "SnacksPickerInput",
        "SnacksPickerInputBorder",
        "SnacksPickerInputTitle",
        "SnacksPickerList",
        "SnacksPickerListBorder",
        "SnacksPickerPreview",
        "SnacksPickerPreviewBorder",
        "SnacksPickerPreviewTitle",
        -- UFO 相关的组
        "UfoFoldedBg",
        "UfoFoldedFg",
        "UfoPreviewSbar",
        "UfoPreviewThumb",
        "UfoPreviewWinBar",
        "UfoPreviewCursorLine",
        "UfoFoldedEllipsis",
        "UfoCursorFoldedLine",
        "UfoPreviewNormal",
        "UfoPreviewBorder",
        "UfoFoldedLinehl",
        -- 折叠预览窗口的背景
        "Folded",
        "FoldColumn",
        "FloatBorder",
        "NormalFloat",
        "ColorColumn",

      },
    },
    config = function(_, opts)
      require("transparent").setup(opts)
      vim.api.nvim_create_autocmd("User", {
        pattern = "TransparentClear",
        desc = "Refresh panel highlights after transparency changes",
        callback = function()
          if package.loaded["astroui.status.heirline"] then
            pcall(require("astroui.status.heirline").refresh_colors)
          end
          vim.cmd.redrawstatus()
          vim.cmd.redrawtabline()
        end,
      })
    end,
  },
}



